---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lovesh Verma.
--- DateTime: 06-06-2021 10:55 AM
---

---Data Listings
ListData = {}
ListData.Query = {
    ["warrants"] = "SELECT mdt_warrants.id, mdt_warrants.incident, mdt_warrants.date, mdt_warrants.approved, mdt_incidents.title AS title, mdt_profiles.image, CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) AS name FROM mdt_warrants LEFT JOIN players ON mdt_warrants.citizenid = players.citizenid LEFT JOIN mdt_incidents ON mdt_warrants.incident = mdt_incidents.id LEFT JOIN mdt_profiles ON mdt_profiles.citizenid = mdt_warrants.citizenid WHERE CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) LIKE @search OR title LIKE @search OR mdt_warrants.incident = @search ORDER BY mdt_warrants.date DESC LIMIT 10",
    ["vehicles"] = "SELECT player_vehicles.vehicle, player_vehicles.plate, CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) AS owner FROM player_vehicles INNER JOIN players ON player_vehicles.citizenid = players.citizenid WHERE player_vehicles.plate LIKE @search LIMIT 10",
    ["profiles"] = "SELECT citizenid, CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) AS name FROM players WHERE citizenid LIKE @search OR CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) LIKE @search LIMIT 10",
    ["incidents"] = "SELECT mdt_incidents.id, mdt_incidents.title, mdt_incidents.date, CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) AS createdbyname, mdt_incidents.createdby FROM mdt_incidents LEFT JOIN players ON mdt_incidents.createdby = players.citizenid WHERE mdt_incidents.title LIKE @searchLike OR mdt_incidents.id = @search ORDER BY mdt_incidents.date DESC LIMIT 10",
    ["reports"] = "SELECT mdt_reports.type, mdt_reports.id, mdt_reports.title, mdt_reports.date, CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) AS createdbyname, mdt_reports.createdby FROM mdt_reports LEFT JOIN players ON mdt_reports.createdby = players.citizenid WHERE mdt_reports.title LIKE @searchLike OR mdt_reports.id = @search ORDER BY mdt_reports.date DESC LIMIT 10",
    ["evidences"] = "SELECT mdt_evidences.id, mdt_evidences.description, mdt_evidences.type, mdt_evidences.date, mdt_evidences.createdby, CONCAT(JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.firstname')), ' ', JSON_UNQUOTE(JSON_EXTRACT(players.charinfo, '$.lastname'))) AS createdbyname FROM mdt_evidences LEFT JOIN players ON players.citizenid = mdt_evidences.createdby WHERE mdt_evidences.description LIKE @searchLike OR mdt_evidences.id = @search ORDER BY mdt_evidences.date DESC LIMIT 10"
}
ListData.QueryParam = function (type, search)
    local escSearch = EscapeSqli(search)
    local searchLike = "%"..escSearch.."%"
    if type == "warrants" or type == "vehicles" or type == "profiles" then return { ["@search"] =  searchLike}
    else return {["@search"] = escSearch, ["@searchLike"] = searchLike} end

end

--Data Loadings
LoadData = {}
LoadData.Query = {
    ["incidents"] = "SELECT * FROM `mdt_incidents` WHERE id=@select LIMIT 1",
    ["reports"] = "SELECT * FROM `mdt_reports` WHERE id=@select LIMIT 1",
}
LoadData.QueryParam = function(id)
    return {["@select"] = id}
end
